# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название товара')),
                ('price', models.CharField(max_length=300, verbose_name='Описание цены')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Сопровождающее фото')),
            ],
        ),
    ]
