# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
